/**
 * Copies pdf.js's runtime support files out of node_modules into public/pdfjs.
 *
 * These are fetched lazily by pdf.js at render time (CJK CMaps, the standard-14
 * font data, the JBIG2/JPX WASM decoders, one ICC profile). Serving them from
 * our own origin is what lets pdf-to-jpg work offline and keeps the "nothing
 * leaves your device" promise honest.
 *
 * public/pdfjs is gitignored and regenerated by `npm run build`, so the repo
 * stays small and the copies can never drift from the installed version.
 */

import { cp, mkdir, rm, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';

const require = createRequire(import.meta.url);

const DIRS = ['cmaps', 'standard_fonts', 'wasm', 'iccs'];

const pdfjsRoot = dirname(require.resolve('pdfjs-dist/package.json'));
const version = require('pdfjs-dist/package.json').version;
const out = join(process.cwd(), 'public', 'pdfjs');

await rm(out, { recursive: true, force: true });
await mkdir(out, { recursive: true });

let copied = 0;
for (const dir of DIRS) {
  const from = join(pdfjsRoot, dir);
  if (!existsSync(from)) {
    console.warn(`sync-pdfjs: pdfjs-dist has no ${dir}/ — skipping`);
    continue;
  }
  await cp(from, join(out, dir), { recursive: true });
  copied++;
}

// A breadcrumb so it is obvious where these came from and that they are generated.
await writeFile(
  join(out, 'README.txt'),
  [
    `Generated by scripts/sync-pdfjs.mjs from pdfjs-dist@${version}.`,
    'Do not edit or commit — run `npm run sync:pdfjs` to recreate.',
    '',
  ].join('\n'),
  'utf8',
);

console.log(`sync-pdfjs: copied ${copied}/${DIRS.length} asset dirs from pdfjs-dist@${version}`);
